name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v3

      - name: Python o'rnatish
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Poetry o'rnatish
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Kutubxonalarni kesh qilish
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.local/share/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Kutubxonalarni o'rnatish
        run: |
          poetry install --only main

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build jarayonini bajarish
        run: |
          # Build jarayoni
          echo "Building project..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: EC2 serverga ulanish va loyihani joylashtirish
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/fastapi
            git pull origin main
            export PATH="$HOME/.local/bin:$PATH"
            poetry install --only main
            pm2 restart fastapi --update-env
            sudo systemctl restart nginx
