name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v3

      - name: Python o'rnatish
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Poetry o'rnatish
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Kutubxonalarni kesh qilish
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.local/share/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Kutubxonalarni o'rnatish
        run: poetry install --only main --no-root

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build jarayonini bajarish
        run: |
          echo "Building project..."
          echo "::group::Building project"
          # Build jarayoni
          echo "::endgroup::"

      - name: Testlarni ishga tushirish
        run: |
          echo "::group::Running tests"
          poetry run pytest
          echo "::endgroup::"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git pull va merge konfliktlarni tekshirish
        run: |
          echo "::group::Fetching and checking for merge conflicts"
          git fetch origin
          git diff --name-only HEAD $(git merge-base HEAD origin/main) || echo "No conflicts detected"
          echo "::endgroup::"

      - name: EC2 serverga ulanish va loyihani joylashtirish
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/fastapi
            git pull origin main || { echo 'Git pull failed'; exit 1; }
            export PATH="$HOME/.local/bin:$PATH"
            poetry install --only main --no-root || { echo 'Poetry install failed'; exit 1; }
            pm2 restart fastapi --update-env || { echo 'PM2 restart failed'; exit 1; }
            sudo systemctl restart nginx || { echo 'Nginx restart failed'; exit 1; }
            pm2 status || { echo 'PM2 status failed'; exit 1; }
