name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v3

      - name: Python o'rnatish
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Poetry o'rnatish
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Poetry versiyasini tekshirish
        run: poetry --version

      - name: Kutubxonalarni o'rnatish
        run: poetry install --only main

      - name: EC2 serverga ulanish va loyihani joylashtirish
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/your-app
            git pull origin main
            export PATH="$HOME/.local/bin:$PATH"
            # PM2 deploy so'roviga asosan post-deploy ishlaydi
            # poetry install va pm2 reload ishlaydi
