name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # O'zgartirish uchun asosiy tarmoq

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Python versiyasi

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install

      - name: Deploy to AWS EC2
        env:
          SERVER_IP: ${{ secrets.HOST }}
          SERVER_USER: ${{ secrets.USERNAME }}
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$DEPLOY_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          scp -i deploy_key.pem -r . $SERVER_USER@$SERVER_IP:/path/to/deploy/
          ssh -i deploy_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
            cd /path/to/deploy/
            poetry install
            pm2 restart fastapi
          EOF
