name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v3

      - name: Python o'rnatish
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Poetry o'rnatish
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          # `PATH` o'zgaruvchisini faqat joriy ish sessiyasiga qo'shamiz
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Poetry versiyasini tekshirish
        run: poetry --version

      - name: Kutubxonalarni o'rnatish
        run: poetry install --no-root --no-dev

      - name: EC2 serverga ulanish va loyihani joylashtirish
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/fastapi
            git pull origin main
            # Faqat o'zgargan fayllarni tekshiramiz
            if [[ $(git diff --name-only HEAD^ | grep -E 'poetry.lock|pyproject.toml') ]]; then
              poetry install --no-dev
            fi
            pm2 restart fastapi --update-env
            sudo systemctl restart nginx
