name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v3

      - name: EC2 serverga ulanish va loyihani joylashtirish
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/fastapi
            git pull origin main

            # Yashirin o'zgaruvchilarni yuklash
            echo "$ENV_FILE_CONTENT" > .env

            # Kerakli paketlarni o'rnatish
            poetry install --only main

            # PM2 va Nginxni yangilash
            pm2 reload ecosystem.config.js
            sudo systemctl restart nginx
            pm2 status
